### PR TITLE
commiting from user

### PR DESCRIPTION
**Pull request by ShubhamK786**

### CODE REVIEW

**Comment by ShubhamK786** [comment]
Added Sum.java

**Comment by sk-shubhamkumar** [comment]
Please add Sub.java also

**Comment by sk-shubhamkumar** [comment]
Hi thanks

**Comment by ShubhamK786** [comment]
Final Commit
Added Hello.java ........ done
Added Sum.java ......... done
Added Sub.java ..........done
Modified Sum.java ......... done

**Pull request merged**
